version: 2

run:
  timeout: 5m

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 120
  gosec:
    severity: medium
    confidence: medium
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  default: fast
  disable:
    - wsl
    - nlreturn
    - predeclared
    - prealloc
    - mnd
    - funlen
    - cyclop
    - depguard
  settings:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
