version: 2

run:
  timeout: 5m

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 120
  gosec:
    severity: medium
    confidence: medium
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  disable:
    - wsl
    - nlreturn
    - predeclared
    - prealloc
    - mnd
    - funlen
    - cyclop
    - depguard

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec