version: "2"

linters:
  default: fast

  disable:
    - wsl
    - nlreturn
    - predeclared
    - prealloc
    - mnd
    - funlen
    - cyclop
    - depguard
    - lll

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
